// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPvjOSEYv60bdXrWzpTKiFFUgBY_qvgI4',
    appId: '1:794353398455:web:d502c6145feac35fd85332',
    messagingSenderId: '794353398455',
    projectId: 'bpr-pms',
    authDomain: 'bpr-pms.firebaseapp.com',
    storageBucket: 'bpr-pms.firebasestorage.app',
    measurementId: 'G-EPC98DP3PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl3-oajsHs8sTFnXiG2mHDVWaugq1A6jQ',
    appId: '1:794353398455:android:f6ce53e96b02f53dd85332',
    messagingSenderId: '794353398455',
    projectId: 'bpr-pms',
    storageBucket: 'bpr-pms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1EwWx1zbHlabA1TaIlOwOxsHCNXr8tpE',
    appId: '1:794353398455:ios:d3d90e183ee73bded85332',
    messagingSenderId: '794353398455',
    projectId: 'bpr-pms',
    storageBucket: 'bpr-pms.firebasestorage.app',
    iosBundleId: 'com.nevmock.bprPms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1EwWx1zbHlabA1TaIlOwOxsHCNXr8tpE',
    appId: '1:794353398455:ios:d3d90e183ee73bded85332',
    messagingSenderId: '794353398455',
    projectId: 'bpr-pms',
    storageBucket: 'bpr-pms.firebasestorage.app',
    iosBundleId: 'com.nevmock.bprPms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPvjOSEYv60bdXrWzpTKiFFUgBY_qvgI4',
    appId: '1:794353398455:web:3818ed6946b4eb9dd85332',
    messagingSenderId: '794353398455',
    projectId: 'bpr-pms',
    authDomain: 'bpr-pms.firebaseapp.com',
    storageBucket: 'bpr-pms.firebasestorage.app',
    measurementId: 'G-3JZP5JBBVG',
  );
}
